stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"

image: mcr.microsoft.com/dotnet/sdk:8.0

cache:
  paths:
    - .nuget/packages

before_script:
  - dotnet --info
  - dotnet restore
  - dotnet tool restore

build:
  stage: build
  script:
    - dotnet build -c Release --no-restore
  artifacts:
    when: always
    paths:
      - "**/bin/Release/**"
    expire_in: 1 week

test:
  stage: test
  script:
    - dotnet test -c Release --no-build --collect:"XPlat Code Coverage" -v minimal
    - dotnet tool run reportgenerator -reports:"tests/**/TestResults/**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:"Html;HtmlSummary;Cobertura;lcov"
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - coverage-report/**
      - tests/**/TestResults/**/coverage.cobertura.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: tests/**/TestResults/**/coverage.cobertura.xml
