name: Format and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore FileProcessor.sln

    - name: Verify formatting
      run: dotnet tool restore && dotnet format --verify-no-changes FileProcessor.sln

    - name: Build
      run: dotnet build FileProcessor.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test FileProcessor.sln --no-build --verbosity minimal
